---
title: "Working proposal-UPCH"
output: 
  flexdashboard::flex_dashboard:
    theme: lumen
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(sf)
library(dplyr)
library(mapview)
library(crosstalk)
library(tidyr)
```

Iquitos - Nauta
==============================================================
### Iquitos - Nauta

```{r echo=FALSE,message=FALSE,warning=FALSE}
villages <- st_read("data/villages_1km.gpkg",quiet = T) %>%
  filter(CPINEI != " ")  %>% 
  select(NOMCP,DIST)  %>%
  mutate(NOMCP = toupper(NOMCP))
comunidad_1 <- c(
  "CAHUIDE","VARILLAL","LOS DELFINES",
  "PEÑA NEGRA","QUISTOCOCHA","AA.HH TERMINAL",
  "AA.HH. VILLA SELVA")

data <- read.csv(
  "data/cp_drones.csv") |>
  mutate(NOMCP = toupper(NOMCP)) |> 
  filter(NOMCP %in% comunidad_1) |> 
  st_drop_geometry() |> 
  select(XGD, YGD,NOMCP) |> 
  rename(lon = XGD,
         lat = YGD,
          cp = NOMCP
         ) |> 
  as_tibble()

nofind <- tibble(
  lat = c(-3.796194,-3.7987158),
  lon = c(-73.2992432,-73.310606),
  cp = c("AA.HH. VILLA SELVA","AA.HH SAN ANTONIO DEL TERMINAL")
)

eje_in <- bind_rows(data,nofind) |> 
  st_as_sf(coords = c("lon","lat"),crs = 4326) |> 
  mutate(color = "old") |> 
  select(cp,color,geometry)

norepeat <- villages[which(!villages$NOMCP %in% eje_in$cp),]
norepeat <- norepeat |> 
  mutate(color = "new") |>
  select(-c(DIST)) |> 
  rename(cp = NOMCP,geometry = geom) |> 
  select(cp,geometry,color)

eje_n1 <- bind_rows(eje_in,norepeat)
mapview(
  eje_n1,
  legend = F,
  zcol = "cp",
  col.regions = c("red","blue"),
  layer.name = "Iquitos-Nauta")
```

Santa Clara-Santo Tomas
=====================================================================

```{r}
comunidad_2 <- c("SANTA CLARA","SANTO TOMAS","RUMOCOCHA") 
data <- read.csv(
  "data/cp_drones.csv") |>
  mutate(NOMCP = toupper(NOMCP)) |> 
  filter(NOMCP %in% comunidad_2) |> 
  st_drop_geometry() |> 
  select(XGD, YGD,NOMCP) |> 
  rename(lon = XGD,
         lat = YGD,
         cp = NOMCP
  ) |> 
  as_tibble()

eje_in <- bind_rows(data,nofind) |> 
  st_as_sf(coords = c("lon","lat"),crs = 4326)

mapview(eje_in, legend = F)
```


Zungarococha
========================================================================
```{r}
comunidad_3 <- c("LLANCHAMA","NINA RUMI","PUERTO ALMENDRA","SANTA ISABEL DE ZUNGARO COCHA")
data <- read.csv(
  "data/cp_drones.csv") |>
  mutate(NOMCP = toupper(NOMCP)) |> 
  filter(NOMCP %in% comunidad_3) |> 
  st_drop_geometry() |> 
  select(XGD, YGD,NOMCP) |> 
  rename(lon = XGD,
         lat = YGD,
         cp = NOMCP
  ) |> 
  as_tibble()

eje_in <- bind_rows(data,nofind) |> 
  st_as_sf(coords = c("lon","lat"),crs = 4326)

mapview(eje_in, legend = F)
```

Other
=====================================================================
```{r}
comunidad_4 <- c("TARAPOTO","HUATURI","SAN PABLO DE CUYANA")
data <- read.csv(
  "data/cp_drones.csv") |>
  mutate(NOMCP = toupper(NOMCP)) |> 
  filter(NOMCP %in% comunidad_4) |> 
  st_drop_geometry() |> 
  select(XGD, YGD,NOMCP) |> 
  rename(lon = XGD,
         lat = YGD,
         cp = NOMCP
  ) |> as_tibble()

eje_in <- bind_rows(data,nofind) |> 
  st_as_sf(coords = c("lon","lat"),crs = 4326)

mapview(eje_in, legend = F)
```
