---
title: "Working proposal - Innovalab"
output: 
  flexdashboard::flex_dashboard:
    favico: https://raw.githubusercontent.com/healthinnovation/innovar/gh-pages/favicon-32x32.png
    logo: https://raw.githubusercontent.com/healthinnovation/innovar/gh-pages/apple-touch-icon-60x60.png
    orientation: columns
    vertical_layout: fill
    navbar:
       - { icon: "fa-github", href: "http://ambarja.github.io", align: right}
    theme: lumen
---
<style>
.navbar-logo{
width:45px;
margin-left: 1px;
}
.navbar-brand {
    float: none;
    }
.dataTables_scrollBody {
    height:400px !important;
    max-height:400px !important;
}
.chart-stage-flex {
    overflow:auto !important;
}
</style>

```{r setup, include=FALSE ,echo=FALSE, warning=FALSE, message=FALSE}
library(flexdashboard)
library(sf)
library(leaflet)
library(DT)
library(crosstalk)
library(dplyr)
library(kableExtra)
road_5km <- st_read("SBD/road_5km.gpkg")
villages5km <- st_read("SBD/villages_5km.gpkg")
villages_db <- st_read("SBD/villages_db.gpkg") %>%
  filter(NOMCP %in% toupper(villages5km$NOMCP)) %>% 
  select(NOMCP,DIST,year,def_areakm_in_5km,ligths_noct_5km) %>% 
  mutate(NOMCP = stringr::str_to_title(NOMCP),
         DIST = stringr::str_to_title(DIST))
sd <- SharedData$new(villages_db)
```

Column {.sidebar data-width=600}
-----------------------------------------------------------------------

<h3 align="center"><strong><u>Route: Iquitos - Nauta</u></strong></h3>

<div align="center">
```{r table}
villages_db |> 
  group_by(DIST) |> 
  summarise(Villages = n(),
            def_areakm_in_5km = sum(def_areakm_in_5km),
            ligths_noct_5km = mean(ligths_noct_5km)) |>
  rename(`Total districts`= DIST,
         `Total villages` = Villages,
          `Deforestation (km2)`= def_areakm_in_5km,
          `Night ligth (index)`= ligths_noct_5km) |>
  st_drop_geometry() |> 
  kableExtra::kable() |> 
  kable_styling()
```
</div>

<h4><strong>Village selected 🔍</strong></h4> 
```{r filters}
filter_select(
  id = "NOMCP",
  label = "",
  sharedData = sd,
  group = ~NOMCP
)
```
<div align="center">
```{r datatable}
sd %>%
  datatable(
    colnames =  c("District","Village","year","deforestation","night ligths"),
    class = "compact",
    width = "100%",
    options = list(
      lengthMenu = list(c(25, 100, -1), c('25', '100', 'All')),
      deferRender = TRUE,
      scrollY = 300,
      scroller = TRUE,
      columnDefs = list(list(className = 'dt-center', targets = 0:4)))
    )
```
</div>

Column {data-width=400}
-----------------------------------------------------------------------

### Web map <i class="icon ion-map"></i>

```{r}
sd |>  
  leaflet() |> 
  addProviderTiles(providers$OpenStreetMap) |> 
  addAwesomeMarkers(
    popup = ~paste0(
    "<h5><strong>Village: ", villages_db$NOMCP, "<strong></h5>"),
    icon = awesomeIcons(
    library = "ion",
    icon = case_when(
     villages_db$DIST == "San Juan Bautista"~ "ion-android-radio-button-on",
     villages_db$DIST == "Nauta" ~ "ion-android-radio-button-on",
     villages_db$DIST == "Belen"~ "ion-android-radio-button-on"
    ),
    iconColor = "white",
    markerColor = case_when(
     villages_db$DIST == "San Juan Bautista"~ "black",
     villages_db$DIST == "Nauta" ~ "blue",
     villages_db$DIST == "Belen"~ "orange"
    )
  )
  ) |> 
  setView(
    lng = -73.446,
    lat = -4.142,
    zoom = 9) |> 
  leaflet.extras::addResetMapButton() |>
  leaflet.extras::addDrawToolbar()
```