---
title: "Working proposal-UPCH"
output: 
  flexdashboard::flex_dashboard:
    theme: lumen
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(sf)
library(dplyr)
library(mapview)
library(crosstalk)
library(tidyverse)
library(leaflet)
library(DT)
library(leaflet.extras)
db <- st_read("data/spdb_drones.gpkg") %>%
  mutate(lon = round(st_coordinates(.)[,1],2),
         lat = round(st_coordinates(.)[,2],2),
         cp = str_to_title(cp)) |> select(cp,ruta,year,Deforestation,Nigth_light,lon,lat)%>% 
  st_drop_geometry()

sp <- st_read("data/db_drones.gpkg")
sp1 <- sp |> filter(ruta == "Iquitos-Nauta")
sp2 <- sp |> filter(ruta == "Santa Clara - Santo Tomas")
sp3 <- sp |> filter(ruta == "Zungarococha")
sp4 <- sp |> filter(ruta == "Other")

ruta1 <- db |> filter(ruta == "Iquitos-Nauta")
ruta2 <- db |> filter(ruta == "Santa Clara - Santo Tomas")
ruta3 <- db |> filter(ruta == "Zungarococha")
ruta4 <- db |> filter(ruta == "Other")
sd1 <- SharedData$new(ruta1)
sd2 <- SharedData$new(ruta2)
sd3 <- SharedData$new(ruta3)
sd4 <- SharedData$new(ruta4)
```

Iquitos - Nauta
==============================================================

Column {.sidebar data-width=700}
--------------------------------------------------------------

<h3><strong>Village selected 🔍</strong></h3> 

```{r filters}
filter_select(
  id = "cp",
  label = "",
  sharedData = sd1,
  group = ~cp
)
```

<div align="center">
```{r}
sd1 %>%
  datatable(
    colnames =  c("Village","Route","Year","Deforestation(km2)","Night ligths(index)","Lon","Lat"),
    class = "compact",
    options = list(
     deferRender = TRUE,
      scrollY = 300,
      scroller = TRUE)
    )
```
</div>


Column {data-width=300}
--------------------------------------------------------------

### Web map <i class="icon ion-map"></i>

```{r echo=FALSE,message=FALSE,warning=FALSE}
 sd1 |>  
  leaflet() |> 
  addProviderTiles(providers$OpenStreetMap) |> 
  addAwesomeMarkers(popup = paste0("<strong>",sp1$cp,"</strong>")) |> 
  addResetMapButton()
```



Santa Clara-Santo Tomas
=====================================================================

Column {.sidebar data-width=700}
--------------------------------------------------------------
<h3><strong>Village selected 🔍</strong></h3> 

```{r}
filter_select(
  id = "cp",
  label = "",
  sharedData = sd2,
  group = ~cp
)
```


<div align="center">
```{r}
sd2 %>%
  datatable(
    colnames =  c("Village","Route","Year","Deforestation(km2)","Night ligths(index)","Lon","Lat"),
    class = "compact",
    width = "100%",
    options = list(
     deferRender = TRUE,
      scrollY = 300,
      scroller = TRUE,
      columnDefs = list(list(className = 'dt-center', targets = 0:4)))
    )
```
</div>

Column {data-width=300}
--------------------------------------------------------------

### Web map <i class="icon ion-map"></i>

```{r echo=FALSE,message=FALSE,warning=FALSE}
 sd2 |>  
  leaflet() |> 
  addProviderTiles(providers$OpenStreetMap) |> 
  addAwesomeMarkers(popup = paste0("<strong>",sp2$cp,"</strong>")) |> 
  addResetMapButton()
```


Zungarococha
========================================================================

Column {.sidebar data-width=700}
--------------------------------------------------------------
<h3><strong>Village selected 🔍</strong></h3> 

```{r}
filter_select(
  id = "cp",
  label = "",
  sharedData = sd3,
  group = ~cp
)
```


<div align="center">
```{r}
sd3 %>%
  datatable(
    colnames =  c("Village","Route","Year","Deforestation(km2)","Night ligths(index)","Lon","Lat"),
    class = "compact",
    width = "100%",
    options = list(
     deferRender = TRUE,
      scrollY = 300,
      scroller = TRUE,
      columnDefs = list(list(className = 'dt-center', targets = 0:4)))
    )
```
</div>

Column {data-width=300}
--------------------------------------------------------------

### Web map <i class="icon ion-map"></i>

```{r echo=FALSE,message=FALSE,warning=FALSE}
 sd3 |>  
  leaflet() |> 
  addProviderTiles(providers$OpenStreetMap) |> 
  addAwesomeMarkers(popup = paste0("<strong>",sp3$cp,"</strong>")) |> 
  addResetMapButton()
```

Other
=====================================================================

Column {.sidebar data-width=700}
--------------------------------------------------------------
<h3><strong>Village selected 🔍</strong></h3> 

```{r}
filter_select(
  id = "cp",
  label = "",
  sharedData = sd4,
  group = ~cp
)
```


<div align="center">
```{r}
sd4 %>%
  datatable(
    colnames =  c("Village","Route","Year","Deforestation(km2)","Night ligths(index)","Lon","Lat"),
    class = "compact",
    width = "100%",
    options = list(
     deferRender = TRUE,
      scrollY = 300,
      scroller = TRUE,
      columnDefs = list(list(className = 'dt-center', targets = 0:4)))
    )
```
</div>

Column {data-width=300}
--------------------------------------------------------------

### Web map <i class="icon ion-map"></i>

```{r echo=FALSE,message=FALSE,warning=FALSE}
 sd4 |>  
  leaflet() |> 
  addProviderTiles(providers$OpenStreetMap) |> 
  addAwesomeMarkers(popup = paste0("<strong>",sp4$cp,"</strong>")) |> 
  addResetMapButton()
```

